name: Deploy to WordPress.org
on:
  push:
    branches:
      - master # Change to your branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4' # Change to your PHP version
        tools: composer:v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    # Build your plugin here if necessary

    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@v2
      env:
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SLUG: your-plugin-slug # Change to your WordPress.org plugin slug
